version: '3'
services:
  frontend:
    container_name: frontend
    image: node:12.12.0-alpine
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/var/www
    ports:
      - 3000:3000
    working_dir: /var/www
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    networks:
      - default
