version: '3'
services:
  frontend:
    container_name: frontend
    image: node:12.12.0-alpine
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/var/www
    ports:
      - 3000:3000
    working_dir: /var/www
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    volumes: 
      - ./backend:/var/www
    env_file: 
      - ./backend/.env
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/local/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    expose: 
      - 80
    depends_on: 
      - backend

